.TH "Capacity.h" 3 "Tue Mar 3 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Capacity.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCCapacity\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBECapacities\fP : unsigned int { \fBSpeed\fP, \fBHealthPoint\fP, \fBArmor\fP, \fBRegeneration\fP, \fBDamage\fP, \fBScope\fP, \fBWeaponSpeed\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBECapacities\fP : unsigned int"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISpeed \fP\fP
.TP
\fB\fIHealthPoint \fP\fP
.TP
\fB\fIArmor \fP\fP
.TP
\fB\fIRegeneration \fP\fP
.TP
\fB\fIDamage \fP\fP
.TP
\fB\fIScope \fP\fP
.TP
\fB\fIWeaponSpeed \fP\fP
.PP
Definition at line 5 of file Capacity\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
