.TH "CArmor" 3 "Sun Mar 1 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CArmor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Armor\&.h>\fP
.PP
Inherits \fBCCapacity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCArmor\fP ()"
.br
.ti -1c
.RI "\fB~CArmor\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcomputeValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 4 of file Armor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CArmor::CArmor ()"
Default constructor of \fBCArmor\fP 
.PP
Definition at line 5 of file Armor\&.cpp\&.
.SS "CArmor::~CArmor ()"

.PP
Definition at line 9 of file Armor\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CArmor::computeValue ()\fC [private]\fP, \fC [virtual]\fP"
Set the value for Armor when Upgrade() is called 
.PP
Implements \fBCCapacity\fP\&.
.PP
Definition at line 15 of file Armor\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
