.TH "CDamage" 3 "Tue Mar 3 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDamage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Damage\&.h>\fP
.PP
Inherits \fBCCapacity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDamage\fP ()"
.br
.ti -1c
.RI "\fB~CDamage\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcomputeValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file Damage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDamage::CDamage ()"
Default constructor of \fBCDamage\fP 
.PP
Definition at line 5 of file Damage\&.cpp\&.
.SS "CDamage::~CDamage ()"

.PP
Definition at line 9 of file Damage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CDamage::computeValue ()\fC [private]\fP, \fC [virtual]\fP"
Set the value for Damage when Upgrade() is called 
.PP
Implements \fBCCapacity\fP\&.
.PP
Definition at line 15 of file Damage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
