.TH "CRegeneration" 3 "Tue Mar 3 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRegeneration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Regeneration\&.h>\fP
.PP
Inherits \fBCCapacity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCRegeneration\fP ()"
.br
.ti -1c
.RI "\fB~CRegeneration\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcomputeValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 4 of file Regeneration\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CRegeneration::CRegeneration ()"
Default constructor of \fBCRegeneration\fP 
.PP
Definition at line 6 of file Regeneration\&.cpp\&.
.SS "CRegeneration::~CRegeneration ()"

.PP
Definition at line 10 of file Regeneration\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CRegeneration::computeValue ()\fC [private]\fP, \fC [virtual]\fP"
Set the value for Regeneration when Upgrade() is called 
.PP
Implements \fBCCapacity\fP\&.
.PP
Definition at line 16 of file Regeneration\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
