.TH "CScope" 3 "Sun Mar 1 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScope \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scope\&.h>\fP
.PP
Inherits \fBCCapacity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCScope\fP ()"
.br
.ti -1c
.RI "\fB~CScope\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcomputeValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 4 of file Scope\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CScope::CScope ()"
Default constructor of \fBCScope\fP 
.PP
Definition at line 6 of file Scope\&.cpp\&.
.SS "CScope::~CScope ()"

.PP
Definition at line 10 of file Scope\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CScope::computeValue ()\fC [private]\fP, \fC [virtual]\fP"
Set the value for Scope when Upgrade() is called 
.PP
Implements \fBCCapacity\fP\&.
.PP
Definition at line 15 of file Scope\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
