.TH "CSpeed" 3 "Sun Mar 1 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSpeed \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Speed\&.h>\fP
.PP
Inherits \fBCCapacity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSpeed\fP ()"
.br
.ti -1c
.RI "\fB~CSpeed\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcomputeValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file Speed\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSpeed::CSpeed ()"
Default constructor of \fBCSpeed\fP 
.PP
Definition at line 6 of file Speed\&.cpp\&.
.SS "CSpeed::~CSpeed ()"

.PP
Definition at line 10 of file Speed\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CSpeed::computeValue ()\fC [private]\fP, \fC [virtual]\fP"
Set the value for Speed when Upgrade() is called 
.PP
Implements \fBCCapacity\fP\&.
.PP
Definition at line 15 of file Speed\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
