.TH "Point.cpp" 3 "Tue Mar 3 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBostream\fP & \fBoperator<<\fP (\fBostream\fP &out, const \fBCPoint\fP &point)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBostream\fP& operator<< (\fBostream\fP & out, const \fBCPoint\fP & point)"
operator<< to print a point 
.PP
\fBParameters:\fP
.RS 4
\fIostream&\fP out - the flow 
.br
\fIconst\fP \fBCPoint\fP& point - the point to print 
.RE
.PP
\fBReturns:\fP
.RS 4
ostream& - the modified flow 
.RE
.PP

.PP
Definition at line 162 of file Point\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
