.TH "Unit.h" 3 "Sun Mar 1 2015" "Version Round1" "BattleIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unit.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCUnit\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBIACODE\fP { \fBLD\fP, \fBHD\fP, \fBL0\fP, \fBH0\fP, \fBL1\fP, \fBH1\fP, \fBL2\fP, \fBH2\fP, \fBL3\fP, \fBH3\fP, \fBL4\fP, \fBH4\fP, \fBL5\fP, \fBH5\fP, \fBL6\fP, \fBH6\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBIACODE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILD \fP\fP
.TP
\fB\fIHD \fP\fP
.TP
\fB\fIL0 \fP\fP
.TP
\fB\fIH0 \fP\fP
.TP
\fB\fIL1 \fP\fP
.TP
\fB\fIH1 \fP\fP
.TP
\fB\fIL2 \fP\fP
.TP
\fB\fIH2 \fP\fP
.TP
\fB\fIL3 \fP\fP
.TP
\fB\fIH3 \fP\fP
.TP
\fB\fIL4 \fP\fP
.TP
\fB\fIH4 \fP\fP
.TP
\fB\fIL5 \fP\fP
.TP
\fB\fIH5 \fP\fP
.TP
\fB\fIL6 \fP\fP
.TP
\fB\fIH6 \fP\fP
.PP
Definition at line 5 of file Unit\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleIA from the source code\&.
